name: Hello World Integração Contínua!

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  OlaMundo: 
    runs-on: ubuntu-latest
    
    steps:
  
        - name: Digam
          run: echo Hello-world!
